#!/bin/bash
# Rendered from targets/debian/deploy.sh.elp. DO NOT edit this file directly.
#
# Runs on the deploy target as root. Reads pre-staged config + certs from
# $STAGING and places them under $INSTALL_BASE, chowning each service tree
# to <svc>:mediaserver. The compose's user: field has the same uid (resolved
# from service_overrides in config.local.yml), so files match the container
# user by owner. See plans/deploy-rebuild.md.
#
# Usage:
#   bash deploy.sh           — apply (the default)
#   bash deploy.sh preview   — dry-run + itemize per-file changes; no mutations
set -euo pipefail

MODE="${1:-apply}"
DRY=""
if [[ "$MODE" == "preview" ]]; then
  DRY="--dry-run --itemize-changes"
fi

STAGING="/opt/fx-mediaserver/staging"
INSTALL_BASE="/opt/fx-mediaserver"

echo "=== fx-wireguard (preserving ownership) ==="
rsync -a $DRY --no-owner --no-group --chmod=Dg+s,Fg+w \
  "$STAGING/fx-wireguard/" "$INSTALL_BASE/config/fx-wireguard/"
echo "=== fx-caddy ==="
rsync -a $DRY --chown=fx-caddy:mediaserver --chmod=Dg+s,Fg+w \
  "$STAGING/fx-caddy/" "$INSTALL_BASE/config/fx-caddy/"
# Recursive chown catches runtime state (data/, logs/, db/) that rsync's
# --chown skips because it's not in the transferred set.
[[ "$MODE" == "apply" ]] && chown -R fx-caddy:mediaserver "$INSTALL_BASE/config/fx-caddy/"
echo "=== fx-sonarr ==="
rsync -a $DRY --chown=fx-sonarr:mediaserver --chmod=Dg+s,Fg+w \
  "$STAGING/fx-sonarr/" "$INSTALL_BASE/config/fx-sonarr/"
# Recursive chown catches runtime state (data/, logs/, db/) that rsync's
# --chown skips because it's not in the transferred set.
[[ "$MODE" == "apply" ]] && chown -R fx-sonarr:mediaserver "$INSTALL_BASE/config/fx-sonarr/"
echo "=== fx-qbittorrent ==="
rsync -a $DRY --chown=fx-qbittorrent:mediaserver --chmod=Dg+s,Fg+w \
  "$STAGING/fx-qbittorrent/" "$INSTALL_BASE/config/fx-qbittorrent/"
# Recursive chown catches runtime state (data/, logs/, db/) that rsync's
# --chown skips because it's not in the transferred set.
[[ "$MODE" == "apply" ]] && chown -R fx-qbittorrent:mediaserver "$INSTALL_BASE/config/fx-qbittorrent/"
echo "=== fx-prometheus ==="
rsync -a $DRY --chown=fx-prometheus:mediaserver --chmod=Dg+s,Fg+w \
  "$STAGING/fx-prometheus/" "$INSTALL_BASE/config/fx-prometheus/"
# Recursive chown catches runtime state (data/, logs/, db/) that rsync's
# --chown skips because it's not in the transferred set.
[[ "$MODE" == "apply" ]] && chown -R fx-prometheus:mediaserver "$INSTALL_BASE/config/fx-prometheus/"

echo "=== systemd units ==="
rsync -a $DRY "$STAGING/systemd/" /etc/systemd/system/
[[ "$MODE" == "apply" ]] && systemctl daemon-reload

echo "Deploy $MODE complete."
