---
name: alertmanager
partof: monitoring
desc: Alert management
port: 9093
sighup_reload: true
scrape_target: true
docker_config:
  image: prom/alertmanager:latest
  volumes:
  - "<%= install_base %>/config/alertmanager:/etc/alertmanager:ro"
  restart: unless-stopped
order: 120
