#!/usr/bin/env ruby
# Golden tests for the renderer.
#
# Renders every ERB template (host-side systemd units + per-service
# templates) against the fixture tree under test/, then diffs against
# checked-in goldens under test/config/.
#
#   ruby test/golden_test.rb               # check
#   UPDATE_GOLDEN=1 ruby test/golden_test.rb  # re-seed

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))
require 'fileutils'
require 'tempfile'
require 'mediaserver/renderer'

FIXTURE_ROOT = File.expand_path('.', __dir__)
GOLDEN_ROOT  = File.expand_path('config', __dir__)
PROJECT_ROOT = File.expand_path('..', __dir__)
UPDATE       = ENV['UPDATE_GOLDEN'] == '1'

def check_or_update(rel_path, content)
  out = File.join(GOLDEN_ROOT, rel_path)
  if UPDATE
    FileUtils.mkdir_p(File.dirname(out))
    File.write(out, content)
    puts "updated #{rel_path}"
    return true
  end
  unless File.exist?(out)
    warn "MISSING golden: #{rel_path} (re-run with UPDATE_GOLDEN=1)"
    return false
  end
  expected = File.read(out)
  return true if expected == content

  warn "DIFF #{rel_path}:"
  Tempfile.create('actual') do |t|
    t.write(content)
    t.flush
    system('diff', '-u', '--label', "golden/#{rel_path}", '--label', 'rendered', out, t.path)
  end
  false
end

def render_template(renderer, abs_path, service_name: nil)
  renderer.render(File.read(abs_path), service_name: service_name)
end

# Mirrors the `--list-make` block in render.rb. Kept in sync by hand;
# render.rb hardcodes root: __dir__ so it can't be reused against
# the fixture tree.
def list_make_output(config)
  dockerized = config.services.select(&:dockerized?)
  systemd_svcs = dockerized.reject(&:has_unit?)
  with_config = systemd_svcs.select do |s|
    Dir.glob(File.join(s.source_dir, '**', '*')).any? do |f|
      File.file?(f) && File.basename(f) != 'service.yml'
    end
  end
  <<~OUT
    # Generated by render.rb --list-make; do not edit.
    ALL_SERVICES := #{config.services.map(&:name).join(' ')}
    DOCKERIZED_SERVICES := #{dockerized.map(&:name).join(' ')}
    SYSTEMD_SERVICES := #{systemd_svcs.map(&:name).join(' ')}
    SIGHUP_SERVICES := #{config.services.select(&:sighup_reload?).map(&:name).join(' ')}
    SERVICES_WITH_CONFIG := #{with_config.map(&:name).join(' ')}
  OUT
end

# Rendered once per dockerized service. Output paths mirror the real
# install layout (see Makefile config/<svc>/ and config/systemd/ rules):
# only docker-compose.yml lives next to the service's app config; the
# systemd units land in a flat config/systemd/ tree.
PER_SERVICE_SYSTEMD = {
  'service.compose.yml.erb'             => ->(s) { File.join(s.name, 'docker-compose.yml') },
  'service.service.erb'                 => ->(s) { File.join('systemd', "#{s.name}.service") },
  'service.path.erb'                    => ->(s) { File.join('systemd', "#{s.name}.path") },
  'service-compose.path.erb'            => ->(s) { File.join('systemd', "#{s.name}-compose.path") },
  'service-compose-reload.service.erb'  => ->(s) { File.join('systemd', "#{s.name}-compose-reload.service") },
}.freeze

def main
  failures = 0
  Dir.chdir(FIXTURE_ROOT) do
    config   = Mediaserver::Config.load(root: '.')
    renderer = Mediaserver::Renderer.new(config)

    config.services.select(&:dockerized?).each do |svc|
      PER_SERVICE_SYSTEMD.each do |tmpl, dst_proc|
        abs = File.join(PROJECT_ROOT, 'systemd', tmpl)
        out = render_template(renderer, abs, service_name: svc.name)
        failures += 1 unless check_or_update(dst_proc.call(svc), out)
      end
      if svc.sighup_reload?
        abs = File.join(PROJECT_ROOT, 'systemd', 'sighup-reload.service.erb')
        out = render_template(renderer, abs, service_name: svc.name)
        failures += 1 unless check_or_update(File.join('systemd', "#{svc.name}-reload.service"), out)
      end
    end

    abs = File.join(PROJECT_ROOT, 'systemd', 'mediaserver.target.erb')
    out = render_template(renderer, abs)
    failures += 1 unless check_or_update('systemd/mediaserver.target', out)

    failures += 1 unless check_or_update('list-make.txt', list_make_output(config))

    Dir.glob('services/*/**/*.erb').sort.each do |rel|
      svc_name = rel.split('/')[1]
      dst = rel.sub(%r{\Aservices/}, '').sub(/\.erb\z/, '')
      out = render_template(renderer, File.expand_path(rel), service_name: svc_name)
      failures += 1 unless check_or_update(dst, out)
    end
  end

  if failures.zero?
    puts UPDATE ? 'all goldens updated' : 'all goldens passed'
    exit 0
  else
    warn "#{failures} golden mismatch(es)"
    exit 1
  end
end

main
