#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path('lib', __dir__))
require 'mediaserver/renderer'

if ARGV.delete('--list-make')
  config = Mediaserver::Config.load(root: __dir__)
  dockerized = config.services.select(&:dockerized?)
  systemd_svcs = dockerized.reject(&:has_unit?)
  with_config = systemd_svcs.select do |s|
    dir = File.expand_path(s.source_dir, __dir__)
    Dir.glob(File.join(dir, '**', '*')).any? do |f|
      File.file?(f) && File.basename(f) != 'service.yml'
    end
  end

  puts "# Generated by render.rb --list-make; do not edit."
  puts "ALL_SERVICES := #{config.services.map(&:name).join(' ')}"
  puts "DOCKERIZED_SERVICES := #{dockerized.map(&:name).join(' ')}"
  puts "SYSTEMD_SERVICES := #{systemd_svcs.map(&:name).join(' ')}"
  puts "SIGHUP_SERVICES := #{config.services.select(&:sighup_reload?).map(&:name).join(' ')}"
  puts "SERVICES_WITH_CONFIG := #{with_config.map(&:name).join(' ')}"
  exit
end

config = Mediaserver::Config.load(root: __dir__)
renderer = Mediaserver::Renderer.new(config)
puts renderer.render(ARGF.read, service_name: ENV['SERVICE_NAME'])
