---
name: blackbox-exporter
partof: monitoring
desc: Blackbox HTTP probe exporter
port: 9115
scrape_target: true
docker_config:
  image: prom/blackbox-exporter:latest
  command:
  - "--config.file=/etc/blackbox-exporter/blackbox.yml"
  volumes:
  - "<%= install_base %>/config/prometheus/blackbox.yml:/etc/blackbox-exporter/blackbox.yml:ro"
  restart: unless-stopped
order: 110
