---
name: node-exporter
partof: monitoring
desc: Host metrics exporter
scrape_target:
  host: host.docker.internal
  port: 9100
  service: operating-system
docker_config:
  image: prom/node-exporter:latest
  network_mode: host
  pid: host
  volumes:
  - "/:/host:ro,rslave"
  command:
  - "--path.rootfs=/host"
  restart: unless-stopped
order: 145
