---
name: prometheus
partof: monitoring
desc: Metrics and alerting
port: 9090
healthz: "/prometheus/-/healthy"
sighup_reload: true
scrape_target:
  metrics_path: /prometheus/metrics
docker_config:
  image: prom/prometheus:latest
  command:
  - "--config.file=/etc/prometheus/prometheus.yml"
  - "--web.external-url=https://<%= hostname %>/prometheus"
  - "--web.route-prefix=/prometheus"
  - "--web.enable-remote-write-receiver"
  volumes:
  - "<%= install_base %>/config/prometheus:/etc/prometheus:ro"
  - "<%= install_base %>/config/prometheus/data:/prometheus/data"
  restart: unless-stopped
order: 100
