---
name: otelcol
partof: monitoring
desc: OpenTelemetry metrics collector
group: docker
docker_config:
  image: otel/opentelemetry-collector-contrib:latest
  command:
  - "--config=/etc/otelcol/otelcol-config.yaml"
  volumes:
  - "<%= install_base %>/config/otelcol:/etc/otelcol:ro"
  - "/var/run/docker.sock:/var/run/docker.sock:ro"
  extra_hosts:
  - host.docker.internal:host-gateway
  restart: unless-stopped
order: 150
