---
name: cadvisor
partof: monitoring
desc: Container metrics exporter
port: 8081
healthz: "/api/v1/machine"
docker_config:
  image: gcr.io/cadvisor/cadvisor:latest
  ports:
  - 8081:8080
  volumes:
  - "/:/rootfs:ro"
  - "/var/run:/var/run:ro"
  - "/sys:/sys:ro"
  - "/var/lib/docker/:/var/lib/docker:ro"
  - "/dev/disk/:/dev/disk:ro"
  privileged: true
  devices:
  - "/dev/kmsg"
  labels:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
  restart: unless-stopped
order: 140
