---
name: exportarr-sonarr
partof: downloading
desc: Sonarr metrics exporter
scrape_target:
  port: 9145
  service: sonarr
docker_config:
  image: ghcr.io/onedr0p/exportarr:latest
  command:
  - sonarr
  - "--url"
  - http://caddy:8989
  - "--api-key"
  - "<%= sonarr_apikey %>"
  - "--port"
  - '9145'
  restart: unless-stopped
order: 170
