---
name: caddy
partof: dashboard
desc: Reverse proxy for VPN services
sighup_reload: true
docker_config:
  image: caddy:latest
  volumes:
  - "${install_base}/config/caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
  - "${install_base}/certs:/etc/caddy/certs:ro"
  ports:
  - 8080:8080
  - 7878:7878
  - 8989:8989
  - 9696:9696
  restart: unless-stopped
order: 10
