---
name: caddy
partof: dashboard
desc: Reverse proxy for VPN services
sighup_reload: true
docker_config:
  image: caddy:latest
  volumes:
  - "<%= install_base %>/config/caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
  - "<%= install_base %>/config/caddy/certs:/etc/caddy/certs:ro"
  ports:
  - 80:80
  - 443:443
  restart: unless-stopped
order: 10
