---
name: radarr
partof: downloading
desc: find movies
port: 7878
healthz: /ping
use_vpn: true
group: mediaserver
docker_config:
  image: lscr.io/linuxserver/radarr:latest
  volumes:
  - "<%= install_base %>/config/radarr:/config"
  - "<%= media_path %>:/data"
  environment:
  - RADARR__SERVER__URLBASE=/radarr
  - "RADARR__AUTH__APIKEY=<%= (for-service :radarr apikey) %>"
  - "RADARR__AUTH__METHOD=External"
  - "RADARR__AUTH__REQUIRED=DisabledForLocalAddresses"
  restart: unless-stopped
api_config:
  api_version: v3
  auth: { type: header, name: X-Api-Key, value: "<%= (for-service :radarr apikey) %>" }
  extra_mutate_query: { forceSave: true }
order: 20
