---
name: prowlarr
partof: downloading
desc: indexer manager
port: 9696
use_vpn: true
docker_config:
  image: lscr.io/linuxserver/prowlarr:latest
  volumes:
  - "<%= install_base %>/config/prowlarr:/config"
  restart: unless-stopped
order: 40
